# Generated by Django 5.2.15 on 2026-07-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_unique_together_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
    ]
