# Generated by Django 5.2.15 on 2026-07-01 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_candidateprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='academic_achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='accomplishments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='competitive_exams',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='employment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='internships',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='key_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_photo',
            field=models.FileField(blank=True, default='', upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
