# Generated by Django 5.2.15 on 2026-07-06 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_candidateprofile_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='academic_achievements',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='competitive_exams',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='internships',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_summary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
